In [1]:
import numpy as np

### condition

In [9]:
arr=np.arange(10)
out=np.where(arr%2==1,-1,arr) # np.where(condition,if true,else)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr1=np.reshape(arr,(2,5))

In [16]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
a=np.linspace(2,10,num=5,dtype='int32')
b=np.linspace(6,12,num=4,dtype='int32')
c=np.intersect1d(a,b,return_indices=True)

In [44]:
c

(array([ 6,  8, 10]),
 array([2, 3, 4], dtype=int64),
 array([0, 1, 2], dtype=int64))

In [58]:
d=np.arange(2,19,2)
index=np.where((d>=5) & (d<=10))
d[index]

array([ 6,  8, 10])

In [16]:
import numpy as np
def maxx(a,b):
    if a>b:
        return a
    else:
        return b 
result=np.vectorize(maxx,otypes=[float]) # similar to map 
print(result([2,4,6,8],[1,5,4,9]))

[2. 5. 6. 9.]


## swap column

In [23]:
df=np.arange(9).reshape(3,3)
print(df)
df[:,(1,0,2)]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## swap row

In [26]:
df[(1,0,2),:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [28]:
df[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [34]:
df[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [40]:
df1=np.random.randint(5,10,(5,3))

In [44]:
df1

array([[9, 9, 8],
       [6, 9, 8],
       [9, 6, 5],
       [6, 6, 9],
       [5, 7, 6]])

In [54]:
np.random.seed(100) # seed execute same random number

# Generate some random numbers
print(np.random.rand(3))

[0.54340494 0.27836939 0.42451759]
